/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as AuthenticatedBacklogRouteImport } from './routes/_authenticated/backlog'
import { Route as AuthenticatedShoppingRouteImport } from './routes/_authenticated/shopping'
import { Route as AuthenticatedSummaryRouteImport } from './routes/_authenticated/summary'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedWeekRouteImport } from './routes/_authenticated/week'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsPrayer_timesRouteImport } from './routes/_authenticated/settings/prayer_times'
import { Route as AuthenticatedSettingsWeekly_patternRouteImport } from './routes/_authenticated/settings/weekly_pattern'
import { Route as AuthenticatedSettingsDay_typesIndexRouteImport } from './routes/_authenticated/settings/day_types/index'
import { Route as AuthenticatedSettingsDay_typesDayTypeIdRouteImport } from './routes/_authenticated/settings/day_types/$dayTypeId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBacklogRoute = AuthenticatedBacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShoppingRoute = AuthenticatedShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSummaryRoute = AuthenticatedSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWeekRoute = AuthenticatedWeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsPrayer_timesRoute =
  AuthenticatedSettingsPrayer_timesRouteImport.update({
    id: '/settings/prayer_times',
    path: '/settings/prayer_times',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsWeekly_patternRoute =
  AuthenticatedSettingsWeekly_patternRouteImport.update({
    id: '/settings/weekly_pattern',
    path: '/settings/weekly_pattern',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsDay_typesIndexRoute =
  AuthenticatedSettingsDay_typesIndexRouteImport.update({
    id: '/settings/day_types/',
    path: '/settings/day_types/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsDay_typesDayTypeIdRoute =
  AuthenticatedSettingsDay_typesDayTypeIdRouteImport.update({
    id: '/settings/day_types/$dayTypeId',
    path: '/settings/day_types/$dayTypeId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/about': typeof AuthenticatedAboutRoute
  '/backlog': typeof AuthenticatedBacklogRoute
  '/shopping': typeof AuthenticatedShoppingRoute
  '/summary': typeof AuthenticatedSummaryRoute
  '/today': typeof AuthenticatedTodayRoute
  '/week': typeof AuthenticatedWeekRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/settings/prayer_times': typeof AuthenticatedSettingsPrayer_timesRoute
  '/settings/weekly_pattern': typeof AuthenticatedSettingsWeekly_patternRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/settings/day_types/$dayTypeId': typeof AuthenticatedSettingsDay_typesDayTypeIdRoute
  '/settings/day_types/': typeof AuthenticatedSettingsDay_typesIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AuthenticatedAboutRoute
  '/backlog': typeof AuthenticatedBacklogRoute
  '/shopping': typeof AuthenticatedShoppingRoute
  '/summary': typeof AuthenticatedSummaryRoute
  '/today': typeof AuthenticatedTodayRoute
  '/week': typeof AuthenticatedWeekRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof AuthenticatedIndexRoute
  '/settings/prayer_times': typeof AuthenticatedSettingsPrayer_timesRoute
  '/settings/weekly_pattern': typeof AuthenticatedSettingsWeekly_patternRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/settings/day_types/$dayTypeId': typeof AuthenticatedSettingsDay_typesDayTypeIdRoute
  '/settings/day_types': typeof AuthenticatedSettingsDay_typesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/backlog': typeof AuthenticatedBacklogRoute
  '/_authenticated/shopping': typeof AuthenticatedShoppingRoute
  '/_authenticated/summary': typeof AuthenticatedSummaryRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/week': typeof AuthenticatedWeekRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/settings/prayer_times': typeof AuthenticatedSettingsPrayer_timesRoute
  '/_authenticated/settings/weekly_pattern': typeof AuthenticatedSettingsWeekly_patternRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/settings/day_types/$dayTypeId': typeof AuthenticatedSettingsDay_typesDayTypeIdRoute
  '/_authenticated/settings/day_types/': typeof AuthenticatedSettingsDay_typesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/backlog'
    | '/shopping'
    | '/summary'
    | '/today'
    | '/week'
    | '/auth/login'
    | '/auth/register'
    | '/settings/prayer_times'
    | '/settings/weekly_pattern'
    | '/settings/'
    | '/settings/day_types/$dayTypeId'
    | '/settings/day_types/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/backlog'
    | '/shopping'
    | '/summary'
    | '/today'
    | '/week'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/settings/prayer_times'
    | '/settings/weekly_pattern'
    | '/settings'
    | '/settings/day_types/$dayTypeId'
    | '/settings/day_types'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/about'
    | '/_authenticated/backlog'
    | '/_authenticated/shopping'
    | '/_authenticated/summary'
    | '/_authenticated/today'
    | '/_authenticated/week'
    | '/auth/login'
    | '/auth/register'
    | '/_authenticated/'
    | '/_authenticated/settings/prayer_times'
    | '/_authenticated/settings/weekly_pattern'
    | '/_authenticated/settings/'
    | '/_authenticated/settings/day_types/$dayTypeId'
    | '/_authenticated/settings/day_types/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/backlog': {
      id: '/_authenticated/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof AuthenticatedBacklogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shopping': {
      id: '/_authenticated/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof AuthenticatedShoppingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/summary': {
      id: '/_authenticated/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof AuthenticatedSummaryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/week': {
      id: '/_authenticated/week'
      path: '/week'
      fullPath: '/week'
      preLoaderRoute: typeof AuthenticatedWeekRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/prayer_times': {
      id: '/_authenticated/settings/prayer_times'
      path: '/settings/prayer_times'
      fullPath: '/settings/prayer_times'
      preLoaderRoute: typeof AuthenticatedSettingsPrayer_timesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/weekly_pattern': {
      id: '/_authenticated/settings/weekly_pattern'
      path: '/settings/weekly_pattern'
      fullPath: '/settings/weekly_pattern'
      preLoaderRoute: typeof AuthenticatedSettingsWeekly_patternRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/day_types/': {
      id: '/_authenticated/settings/day_types/'
      path: '/settings/day_types'
      fullPath: '/settings/day_types/'
      preLoaderRoute: typeof AuthenticatedSettingsDay_typesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/day_types/$dayTypeId': {
      id: '/_authenticated/settings/day_types/$dayTypeId'
      path: '/settings/day_types/$dayTypeId'
      fullPath: '/settings/day_types/$dayTypeId'
      preLoaderRoute: typeof AuthenticatedSettingsDay_typesDayTypeIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedBacklogRoute: typeof AuthenticatedBacklogRoute
  AuthenticatedShoppingRoute: typeof AuthenticatedShoppingRoute
  AuthenticatedSummaryRoute: typeof AuthenticatedSummaryRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedWeekRoute: typeof AuthenticatedWeekRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSettingsPrayer_timesRoute: typeof AuthenticatedSettingsPrayer_timesRoute
  AuthenticatedSettingsWeekly_patternRoute: typeof AuthenticatedSettingsWeekly_patternRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSettingsDay_typesDayTypeIdRoute: typeof AuthenticatedSettingsDay_typesDayTypeIdRoute
  AuthenticatedSettingsDay_typesIndexRoute: typeof AuthenticatedSettingsDay_typesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedBacklogRoute: AuthenticatedBacklogRoute,
  AuthenticatedShoppingRoute: AuthenticatedShoppingRoute,
  AuthenticatedSummaryRoute: AuthenticatedSummaryRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedWeekRoute: AuthenticatedWeekRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSettingsPrayer_timesRoute:
    AuthenticatedSettingsPrayer_timesRoute,
  AuthenticatedSettingsWeekly_patternRoute:
    AuthenticatedSettingsWeekly_patternRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedSettingsDay_typesDayTypeIdRoute:
    AuthenticatedSettingsDay_typesDayTypeIdRoute,
  AuthenticatedSettingsDay_typesIndexRoute:
    AuthenticatedSettingsDay_typesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
